checks:
    php: true
filter:
    excluded_paths:
        - 'Test/*'
tools:
    external_code_coverage:
        timeout: 2400
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            within:
                brackets: true
