sudo: required

services:
  - docker

language: php

before_script:
  - composer install
  - mkdir -p build/logs

script:
  - docker run -v /home/travis/build/webstream-framework/IO:/workspace/ webstream/module-io vendor/bin/phpunit --configuration phpunit.xml

after_script:
  - vendor/bin/test-reporter

php:
  - 7.0

addons:
  code_climate:
    repo_token:
      secure: "kKI/II9aqMtZIrPbTaWMR6OavOsFD2n2GS3DdKLVviyTbPhHW1KDYCFdTXCyVvM1pEvkfc5fQt2fCHOYOCdiIdN957Ewe6zmFrUoZDgUiFAkZaoH3tR+RgRh2F2WWjcBk8DgnD3x3ofXmbYb/N3tdwFtpRsolkZuRuvOLGK2Qnzfu4qe9GRxXmkFm42wjV0FNI1drzmdTQAa2obWSqsSptDNJ5ktwdiTRiIGXnsjCOUIBrJzL+21loeh5t0yeS/3nw7w28seD5BKbHUEZe62+3E3f24fy8e7mFYysKUNNc9Zumznm8CKnK0Byyn1cq0iXrta3rL++xjTmw8Cace4V9lEuN1ods7LcsL7aNqKOgnszjSHebAvfrIRYfo1H3ra4wkDod5Qax+YXU0vyZWqIUTA5TsXZ38CNviUDK9woDU001K57EYiXkp0S+sAR5/8Ej5MzQi+eaKlE9F3r20tw+wwWtcmYC3TBrNGnrnB2WM/zq3966CYhHtb5KbWm+gBKKY/bJUQ4LcJnF8F9Q8cHhBdE9uTQgaz0aOP4nRR5nWprcJpWepiTWhKxrYaWSfFzP8Z9UuogPAciAO50bd3l8rYNitfr3eflK7cJj0w3L0RSxXfSsfQpiHGoxhFk/pbacAo/iaEspNJ7aPGsg/si3n3a5SXvd2IVcmsiwrAJ5w="

notifications:
  slack:
    secure: tobcQWs5nYA4dk9FkGsYEc7NKTOfwwB43eu4mAa6Iqmr5rRF8fpj0iebwfTrkXBcOCbqfwbr4OMWQ2Dq5PuAp0NlCkHGBr6QH4COzjopO/qOSllVkxnlwi/SKYLcrLdtWdwUCJRbpp72UWCJgq/mhP1ksJf6TtlzpCc5fkO0gxJNUvMb/uUqKUWebHK4bNtNTWE5ffy7Mnxh33Ad+CTV0bqPRuRgwkh0kR4lv/83ew+EzXkxzFPppy4BJMtuBqSDx2RFsY5d8ejwVTJzVz1JLMAKzvrf5VXU+EndeaIx68zDT0bwwyq2H07ovVrL4CTkbI2a4yJDZHPhLee9JQ1fVIS7idV30ChY8drsI1xQDKYkE/vaXjlKE/cB6uOE245X+Ht6uhILTJpwjHSu0CHX3RdyWSXnSg0AsaPZN2g/58W9CzfAK9w6tgVPtxhAE81L+7De9BehEfyUfDN5EN1o4C1KWH9LLw8z6Ha19DG2d/xhJOWSMFu64TiwkuQ3lb14x/R/bcO8rJpxcpnTp10r6NIRAMJKnbMiOmmzgu7EONiUPkjIFuf57p7/rCjGLCqE8OYOhh/xt1sWzn0T17ztzKTlhoJtBq6pvkbRY8OdGsfjUvlvbEJG9zi2qqv2d8DLhGXtFWu39+A1YfEwrdi/BANuLx7vLYHYRczjveyWAlw=
