version: '3'
services:
  webstream-framework-io:
    build: ./
    image: webstream-framework/io
    container_name: webstream-framework-io
    volumes:
        - ./:/workspace
    working_dir: /workspace
    tty: true
    networks:
      - webstream_framework
networks:
  webstream_framework:
    external: true